In [33]:
import pandas as add_pd
import pickle
import numpy as add_np
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import os

In [34]:
# Membaca dataset
anime = add_pd.read_csv("anime.csv", encoding='latin1')

In [35]:
anime.shape

(17562, 35)

In [36]:
anime.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,ã«ã¦ãã¼ã¤ãããã,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,ã«ã¦ãã¼ã¤ãããã å¤©å½ã®æ,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,ãã©ã¤ã¬ã³,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ã¦ã¤ãããã³ã¿ã¼ã...,TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,åéºçãã£ã,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [37]:
anime.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,ã«ã¦ãã¼ã¤ãããã,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,ã«ã¦ãã¼ã¤ãããã å¤©å½ã®æ,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,ãã©ã¤ã¬ã³,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ã¦ã¤ãããã³ã¿ã¼ã...,TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,åéºçãã£ã,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [38]:
anime.columns

Index(['MAL_ID', 'Name', 'Score', 'Genres', 'English name', 'Japanese name',
       'Type', 'Episodes', 'Aired', 'Premiered', 'Producers', 'Licensors',
       'Studios', 'Source', 'Duration', 'Rating', 'Ranked', 'Popularity',
       'Members', 'Favorites', 'Watching', 'Completed', 'On-Hold', 'Dropped',
       'Plan to Watch', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6',
       'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1'],
      dtype='object')

In [39]:
anime = anime[
    [
       "Name",
        "Genres",
        "Type",
        "Episodes",
        "Studios",
        "Duration",
        "Score",
        "Popularity",
        "Rating"
    ]
]

In [40]:
anime.isnull().sum()

Name          0
Genres        0
Type          0
Episodes      0
Studios       0
Duration      0
Score         0
Popularity    0
Rating        0
dtype: int64

In [41]:
anime.duplicated().sum()

np.int64(0)

In [42]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        17562 non-null  object
 1   Genres      17562 non-null  object
 2   Type        17562 non-null  object
 3   Episodes    17562 non-null  object
 4   Studios     17562 non-null  object
 5   Duration    17562 non-null  object
 6   Score       17562 non-null  object
 7   Popularity  17562 non-null  int64
 8   Rating      17562 non-null  object
dtypes: int64(1), object(8)
memory usage: 1.2+ MB

Pada tahap data cleaning dilakukan pemeriksaan terhadap data kosong (missing value) dan data duplikat menggunakan fungsi isnull().sum() dan duplicated().sum(). Hasil pemeriksaan menunjukkan bahwa dataset tidak memiliki data kosong maupun data duplikat, sehingga tidak diperlukan proses penghapusan atau perbaikan data. Oleh karena itu, dataset dapat langsung digunakan pada tahap preprocessing berikutnya.

In [43]:
anime.describe()

         Popularity
count  17562.000000
mean    8763.452340
std     5059.327278
min        0.000000
25%     4383.500000
50%     8762.500000
75%    13145.000000
max    17565.000000

In [44]:
anime.head()

,Name,Genres,Type,Episodes,Studios,Duration,Score,Popularity,Rating
0,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,Sunrise,24 min. per ep.,8.78,39,R - 17+ (violence & profanity)
1,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,Bones,1 hr. 55 min.,8.39,518,R - 17+ (violence & profanity)
2,Trigun,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,Madhouse,24 min. per ep.,8.24,201,PG-13 - Teens 13 or older
3,Witch Hunter Robin,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,Sunrise,25 min. per ep.,7.27,1467,PG-13 - Teens 13 or older
4,Bouken Ou Beet,"Adventure, Fantasy, Shounen, Supernatural",TV,52,Toei Animation,23 min. per ep.,6.98,4369,PG - Children

In [45]:
anime["Type"].unique()

array(['TV', 'Movie', 'OVA', 'Special', 'ONA', 'Music', 'Unknown'],
      dtype=object)

In [46]:
anime["Rating"].unique()

array(['R - 17+ (violence & profanity)', 'PG-13 - Teens 13 or older',
       'PG - Children', 'R+ - Mild Nudity', 'G - All Ages', 'Rx - Hentai',
       'Unknown'], dtype=object)

In [47]:
anime["Studios"].head()

0           Sunrise
1             Bones
2          Madhouse
3           Sunrise
4    Toei Animation
Name: Studios, dtype: object

In [48]:
anime["Genres"].head()

0      Action, Adventure, Comedy, Drama, Sci-Fi, Space
1                Action, Drama, Mystery, Sci-Fi, Space
2    Action, Sci-Fi, Adventure, Comedy, Drama, Shounen
3    Action, Mystery, Police, Supernatural, Drama, ...
4            Adventure, Fantasy, Shounen, Supernatural
Name: Genres, dtype: object

In [49]:
anime["Duration"].head()

0    24 min. per ep.
1      1 hr. 55 min.
2    24 min. per ep.
3    25 min. per ep.
4    23 min. per ep.
Name: Duration, dtype: object

In [50]:
anime["Episodes"].head()

0    26
1     1
2    26
3    26
4    52
Name: Episodes, dtype: object

In [51]:
anime["Score"].describe()

count       17562
unique        533
top       Unknown
freq         5141
Name: Score, dtype: object

In [52]:
anime["Popularity"].describe()

count    17562.000000
mean      8763.452340
std       5059.327278
min          0.000000
25%       4383.500000
50%       8762.500000
75%      13145.000000
max      17565.000000
Name: Popularity, dtype: float64

In [53]:
# Membuat fitur gabungan untuk Content-Based Filtering
anime["features"] = (
    anime["Genres"] + " " +
    anime["Type"] + " " +
    anime["Studios"] + " " +
    anime["Rating"]
)

In [54]:
# Melihat hasil fitur gabungan
anime[["Name", "features"]].head()

,Name,features
0,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Spac..."
1,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space Movie Bo..."
2,Trigun,"Action, Sci-Fi, Adventure, Comedy, Drama, Shou..."
3,Witch Hunter Robin,"Action, Mystery, Police, Supernatural, Drama, ..."
4,Bouken Ou Beet,"Adventure, Fantasy, Shounen, Supernatural TV T..."

In [55]:
# Mengecek tipe data fitur numerik
anime[["Episodes", "Score", "Popularity"]].dtypes

Episodes      object
Score         object
Popularity     int64
dtype: object

Menggabungkan beberapa atribut anime menjadi satu fitur agar dapat diproses menggunakan TF-IDF.

In [56]:
# Membuat objek TF-IDF
tfidf = TfidfVectorizer(stop_words='english')

In [57]:
# Mengubah fitur teks menjadi matriks TF-IDF
tfidf_matrix = tfidf.fit_transform(anime["features"])

In [58]:
# Melihat ukuran matriks TF-IDF
tfidf_matrix.shape

(17562, 880)

In [59]:
# Melihat beberapa kata yang dipelajari TF-IDF
tfidf.get_feature_names_out()[:20]

array(['10', '10gauge', '13', '17', '1in', '1neo', '1st', '21', '33',
       '3hz', '3xcube', '4â', '80', '81', '88', '8bit', 'academy', 'acc',
       'acca', 'actas'], dtype=object)

In [60]:
# Menghitung kemiripan antar anime
cosine_sim = cosine_similarity(tfidf_matrix)

In [61]:
# Melihat ukuran matriks kemiripan
cosine_sim.shape

(17562, 17562)

In [62]:
# Membuat model KNN
knn = NearestNeighbors(
    n_neighbors=10,
    metric='cosine'
)

In [63]:
# Melatih model KNN
knn.fit(tfidf_matrix)

NearestNeighbors(metric='cosine', n_neighbors=10)

In [64]:


# Ubah dari float64 ke float32
cosine_sim = cosine_sim.astype(add_np.float32)

# Folder penyimpanan
save_path = "model"
os.makedirs(save_path, exist_ok=True)

# Simpan TF-IDF
with open(os.path.join(save_path, "tfidf.pkl"), "wb") as file:
    pickle.dump(tfidf, file)

# Simpan cosine similarity
with open(os.path.join(save_path, "cosine_similarity.pkl"), "wb") as file:
    pickle.dump(cosine_sim, file, protocol=pickle.HIGHEST_PROTOCOL)

print(f"File berhasil disimpan di: {save_path}")

File berhasil disimpan di: model

In [65]:
# Menyimpan model KNN
with open("knn_model.pkl", "wb") as file:
    pickle.dump(knn, file)

In [66]:
anime = anime[
    [
        "Name",
        "Genres",
        "Type",
        "Episodes",
        "Studios",
        "Duration",
        "Score",
        "Popularity",
        "Rating"
    ]
]

# Simpan dataset hasil preprocessing
anime.to_csv("anime_clean.csv", index=False)

print("anime_clean.csv berhasil disimpan")

anime_clean.csv berhasil disimpan